env: "real"
planning_group: "ur_manipulator"
mode: 0 # INIT = 0 # TELEOP = 1 # TASK_CONTROL = 2 # JOINT_CONTROL = 3 # AI = 4 # MOVEIT = 5 # IDLE = 6
haptic_feedback: false
base_controller: "scaled_joint_trajectory_controller"
position_controller: "forward_position_controller"
velocity_controller: "forward_velocity_controller"
input_pos_gain: 0.00008
input_ori_gain: 0.00016
task_p_gain: 3.0
task_d_gain: 3
init_pose: [0.498, 0.165, 0.498, 1.518, 0.000, 1.580]
init_joint_states: [0.0, -1.8397, 2.03, -0.2435, 1.5615, 0.0]
base_link: "base_link"
end_effector_link: "wrist_3_link"
ft_sensor_node: "can_rx_filtered"
tf_ft_node: "transformed_ft"
ft_num_measure: 1000 # 1000Hz, 1 sec
ft_raw_save_to: "tool_gravity_ft_raw.json"
ft_zero_save_to: "zero_ft_raw.json"
tf_ft_save_to: "tool_gravity_ft_raw_tf.json"
tool_cg_saved: "tool_cg.json"
set_axis: "z"
thresh_num_measure: 1000
thresh_offset: 0.3
force_thresh_offset: 0.05 # threshold = maximum_value * (1 + offset) 
torque_thresh_offset: 0.03
# force_thresh: [1.3, 0.5, 0.9]
force_pose_gain: 0.00008
# torque_thresh: [0.1, 0.1, 0.1]
torque_pose_gain: 0.2

trajectory_saving_path: "trajectory_data"
trajectory_saving_name: "trajectory.json"